controllers/BookController.php
<?php

namespace app\controllers;

use app\models\Borrowing;
use Yii;
use app\models\Book;
use app\models\BookSearch;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BookController implements the CRUD actions for Book model.
 */
class BookController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['preview', 'borrow', 'out-of-inventory'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['index', 'view', 'create', 'delete', 'update'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Preview Book to Readers
     * @param $id
     *
     * @return string
     */
    public function actionPreview($id)
    {
        return $this->render('preview', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionBorrow($id)
    {
        $book = $this->findModel($id);
        $user = Yii::$app->user;
        $borrowing = new Borrowing();
        $borrowing->status = Borrowing::STATUS_ON_HOLD;
        $borrowing->user_id = $user->id;
        $borrowing->book_id = $id;

        if($borrowing->save()) {
            //Send email to the user with the advice of 3 days to get the book from library
            Yii::$app->mailer->compose('book-requested')
                ->setTo($user->identity->email)
                ->setFrom([Yii::$app->params['adminEmail'] => 'BubbleBook Librarian'])
                ->setSubject(Yii::t('app', 'BubbleBook material ready for pickup'))
                ->send();

            Yii::$app->session->setFlash('bookRequest');
            return $this->redirect('/');
        }

        Yii::$app->session->setFlash('errorBorrowing');
        return $this->redirect(Url::toRoute(['/book/preview', 'id' => $id]));

    }

    /**
     * Lists all Book models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BookSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    /**
     * Lists all Book out of inventory.
     * @return mixed
     */
    public function actionOutOfInventory()
    {
        $searchModel = new BookSearch(['existence' => 0]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('out_of_inventory', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }



    /**
     * Displays a single Book model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Book model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Book();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Book model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Book model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Book model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Book the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Book::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;


use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\ContactForm;
use app\models\BookSearch;
use Faker\Factory;

class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        $searchModel = new BookSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'book_count' => $dataProvider->totalCount,
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider
        ]);
    }

    public function actionGenerate()
    {
        if(!Yii::$app->user->isGuest && Yii::$app->user->can('admin')) {
            $start = microtime(true);
            $faker = Factory::create();
            $data = [];
            for($i=1; $i <= 10; $i++) {
                $existence = rand(1, 50);
                $data[$i] = [
                    $faker->isbn10,
                    $faker->name,
                    $faker->sentence(6),
                    $faker->randomElement(['Adventures','Comedy','Novels','Sci-Fi']),
                    $faker->dateTimeThisCentury->format('Y-m-d'),
                    $existence,
                    $existence,
                    $faker->randomFloat(2,0,100),
                    $faker->realText(100, 1),
                    $faker->dateTime->format('Y-m-d H:i:s')
                ];
            }
            Yii::$app->db->createCommand()->batchInsert('books', ['isbn', 'author', 'title', 'genre', 'publication_date', 'existence', 'total_inventory', 'price', 'review', 'created_at'], $data)->execute();

            $time_elapsed_us = microtime(true) - $start;
            
            $this->redirect(Yii::$app->homeUrl);
        } else {
            $this->redirect(Yii::$app->homeUrl);
        }
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Displays Circulation Policies page.
     *
     * @return string
     */
    public function actionCirculationPolicies()
    {
        return $this->render('policies');
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => 'BubbleBooks',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);

    $items = [
        ['label' => Yii::t('app','Home'), 'url' => ['/site/index']],
        ['label' => Yii::t('app','About'), 'url' => ['/site/about']],
        ['label' => Yii::t('app','Contact'), 'url' => ['/site/contact']],
    ];
    if(Yii::$app->user->isGuest) {
        $items[] = ['label' => Yii::t('app','Register'), 'url' => ['/user/register']];
        $items[] = ['label' => Yii::t('app','Login'), 'url' => ['/user/login']];
    } else {
        if(Yii::$app->user->can('admin')) {
            $items[] = ['label' => '<span class="glyphicon glyphicon-cog"></span> ' . Yii::t('app','Admin'), 'items' => [
                '<li class="dropdown-header">' . Yii::t('app','User Admin') . '</li>',
                ['label' => Yii::t('app','User List'), 'url' => ['/user/admin']],
                ['label' => Yii::t('app','Add New User'), 'url' => ['/user/admin/create']],
                '<li class="divider"></li>',
                '<li class="dropdown-header">' . Yii::t('app','Books') . '</li>',
                ['label' => Yii::t('app','Books Inventory'), 'url' => ['/book/index']],
                ['label' => Yii::t('app','Add New Book'), 'url' => ['/book/create']],
                ['label' => Yii::t('app','Out of Inventory'), 'url' => ['/book/out-of-inventory']],
                ['label' => Yii::t('app','Generate 10 Books'), 'url' => ['/site/generate']],
                '<li class="divider"></li>',
                '<li class="dropdown-header">' . Yii::t('app','Library Service') . '</li>',
                ['label' => Yii::t('app','All Book Requests'), 'url' => ['/borrowing/index']],
                ['label' => Yii::t('app','Books for Pickup'), 'url' => ['/borrowing/pickups']],
                ['label' => Yii::t('app','Books Returned'), 'url' => ['/borrowing/returned']],
                ['label' => Yii::t('app','Overdue Lends'), 'url' => ['/borrowing/overdue-lends']],
            ]];
        }
        $items[] = ['label' => '<span class="glyphicon glyphicon-user"></span> ' . Yii::t('app','Welcome') .  ', ' . Yii::$app->user->displayName, 'items' => [
            ['label' => Yii::t('app','Profile'), 'url' => ['/user/profile']],
            ['label' => Yii::t('app','Personal Library'), 'url' => ['/borrowing/my-books']],
            '<li class="divider"></li>',
            ['label' => '<span class="glyphicon glyphicon-off"></span> ' . Yii::t('app','Logout'),
                'url' => ['/user/logout'],
                'linkOptions' => ['data-method' => 'post']
            ]
        ]];
    }

    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'encodeLabels' => false,
        'items' => $items
    ]);

    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">
            &copy; Library BubbleUp <?= date('Y') ?>. 
            Please, read our <?= Html::a(Yii::t('app', 'Circulation Policies'), '/site/circulation-policies'); ?>. Thanks!
        </p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>