controllers/BookController.php
<?php

namespace app\controllers;

use app\models\Borrowing;
use Yii;
use app\models\Book;
use app\models\BookSearch;
use yii\filters\AccessControl;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BookController implements the CRUD actions for Book model.
 */
class BookController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['preview', 'borrow', 'out-of-inventory'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => ['index', 'view', 'create', 'delete', 'update'],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Preview Book to Readers
     * @param $id
     *
     * @return string
     */
    public function actionPreview($id)
    {
        return $this->render('preview', [
            'model' => $this->findModel($id),
        ]);
    }

    public function actionBorrow($id)
    {
        $book = $this->findModel($id);
        $user = Yii::$app->user;
        $borrowing = new Borrowing();
        $borrowing->status = Borrowing::STATUS_ON_HOLD;
        $borrowing->user_id = $user->id;
        $borrowing->book_id = $id;

        if($borrowing->save()) {
            //Send email to the user with the advice of 3 days to get the book from library
            Yii::$app->mailer->compose('book-requested')
                ->setTo($user->identity->email)
                ->setFrom([Yii::$app->params['adminEmail'] => 'BubbleBook Librarian'])
                ->setSubject(Yii::t('app', 'BubbleBook material ready for pickup'))
                ->send();

            Yii::$app->session->setFlash('bookRequest');
            return $this->redirect('/');
        }

        Yii::$app->session->setFlash('errorBorrowing');
        return $this->redirect(Url::toRoute(['/book/preview', 'id' => $id]));

    }

    /**
     * Lists all Book models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BookSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
    /**
     * Lists all Book out of inventory.
     * @return mixed
     */
    public function actionOutOfInventory()
    {
        $searchModel = new BookSearch(['existence' => 0]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('out_of_inventory', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }



    /**
     * Displays a single Book model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Book model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Book();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Book model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Book model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Book model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Book the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Book::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/BorrowingController.php
<?php

namespace app\controllers;

use app\models\Book;
use app\models\Profile;
use app\models\User;
use Carbon\Carbon;
use Yii;
use app\models\Borrowing;
use app\models\BorrowingSearch;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BorrowingController implements the CRUD actions for Borrowing model.
 */
class BorrowingController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['my-books'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => [
                            'index',
                            'view',
                            'create',
                            'delete',
                            'update',
                            'returned',
                            'return-book',
                            'pickup',
                            'pickups',
                            'overdue-lends',
                            'overdue-email',
                            'overdue-bulk'
                        ],
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                    'pickup' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Borrowing models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BorrowingSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Borrowing Ready for Pickup.
     * @return mixed
     */
    public function actionPickups()
    {
        $searchModel = new BorrowingSearch(['status' => Borrowing::STATUS_ON_HOLD]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('pickups', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Borrowing Ready for Pickup.
     * @return mixed
     */
    public function actionReturned()
    {
        $searchModel = new BorrowingSearch(['status' => Borrowing::STATUS_RETURNED]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('returned', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Borrowing Ready for Pickup.
     * @return mixed
     */
    public function actionOverdueLends()
    {
        $searchModel = new BorrowingSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, 'overdue');

        return $this->render('overdue_lends', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Lists all Borrowing By the Current User.
     * @return mixed
     */
    public function actionMyBooks()
    {
        $searchModel = new BorrowingSearch(['user_id' => Yii::$app->user->id]);
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('my_books', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }



    /**
     * Displays a single Borrowing model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Borrowing model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Borrowing();
        $all_books = ArrayHelper::map(Book::find()->all(), 'id', 'title');
        $all_readers = ArrayHelper::map(User::find()->all(), 'id', 'displayName');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
                'books' => $all_books,
                'readers' => $all_readers
            ]);
        }
    }

    /**
     * Updates an existing Borrowing model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $all_books = ArrayHelper::map(Book::find()->all(), 'id', 'title');
        $all_readers = ArrayHelper::map(User::find()->all(), 'id', 'displayName');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'books' => $all_books,
                'readers' => $all_readers
            ]);
        }
    }

    /**
     * Deletes an existing Borrowing model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Pickup the book at the Library
     * @param integer $id
     * @return \yii\web\Response
     */
    public function actionPickup($id)
    {
        /** @var Borrowing $model */
        $model = $this->findModel($id);
        if($model->book->existence <= 0) {
            Yii::$app->session->setFlash('zeroExistence');
            return $this->redirect(['pickups']);
        }
        $now = Carbon::now();
        $model->borrowed_date = $now;
        $model->due_date = $now->copy()->addDays(Borrowing::MAX_LOAN_DAYS);
        $model->status = Borrowing::STATUS_HELD;
        $model->book->decrementExistence();
        $model->save();

        return $this->redirect(['index']);
    }

    /**
     * Return this Book to the Inventory
     * @param $id
     * @return \yii\web\Response
     */
    public function actionReturnBook($id)
    {
        $model = $this->findModel($id);
        $now = Carbon::now();
        if(empty($model->borrowed_date)) {
            $model->borrowed_date = $now;
            $model->due_date = $now->copy()->addDays(Borrowing::MAX_LOAN_DAYS);
        }
        $model->returned_date = $now;
        $model->status = Borrowing::STATUS_RETURNED;
        $model->book->increaseExistence();
        if($model->save()) {
            Yii::$app->mailer->compose('book-returned')
                ->setTo($model->user->email)
                ->setFrom([Yii::$app->params['adminEmail'] => 'BubbleBook Librarian'])
                ->setSubject(Yii::t('app', 'BubbleBook material returns to the Library. Thanks'))
                ->send();

            Yii::$app->session->setFlash('bookRequest');
        }

        return $this->redirect(['index']);
    }

    /**
     * Send Individual Email after Overdue
     * @param $id
     * @return \yii\web\Response
     */
    public function actionOverdueEmail($id)
    {
        $model = $this->findModel($id);
        Yii::$app->mailer->compose('book-overdue')
            ->setTo($model->user->email)
            ->setFrom([Yii::$app->params['adminEmail'] => 'BubbleBook Librarian'])
            ->setSubject(Yii::t('app', 'Warning! Some fees will applied cause your overdue.'))
            ->send();

        Yii::$app->session->setFlash('bookOverdue');

        return $this->redirect(['overdue-lends']);
    }

    /**
     * Send Bulk Email to Overdues
     * @return \yii\web\Response
     */
    public function actionOverdueBulk()
    {
        $items = Borrowing::find()->with('book')->with('user')->overdue()->all();
        $emails = [];
        foreach ($items as $item) {
            /** @var Borrowing $item */
            $emails[$item->user->email] = $item->user->displayName;
        }
        Yii::$app->mailer->compose('book-overdue')
            ->setTo($emails)
            ->setFrom([Yii::$app->params['adminEmail'] => 'BubbleBook Librarian'])
            ->setSubject(Yii::t('app', 'Warning! Some fees will applied cause your overdue.'))
            ->send();

        Yii::$app->session->setFlash('bulkOverdue');

        return $this->redirect(['overdue-lends']);
    }

    /**
     * Finds the Borrowing model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Borrowing the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Borrowing::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

views/borrowing/_form.php
<?php

use yii\helpers\Html;
use kartik\widgets\ActiveForm;
use kartik\widgets\DatePicker;
use kartik\widgets\Select2;

/* @var $this yii\web\View */
/* @var $model app\models\Borrowing */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="borrowing-form">

    <?php $form = ActiveForm::begin([
        'id' => 'form-borrowing-entry',
        'type' => ActiveForm::TYPE_VERTICAL
    ]); ?>

    <?= $form->field($model, 'borrowed_date')->widget(DatePicker::classname(), [
        'options' => ['placeholder' => 'Date of Reader Pickup?'],
        'pluginOptions' => [
            'autoclose'=>true,
            'format' => 'yyyy-mm-dd',
            'todayHighlight' => true
        ]
    ]); ?>

    <?= $form->field($model, 'due_date')->widget(DatePicker::classname(), [
        'options' => ['placeholder' => 'Due Date?'],
        'pluginOptions' => [
            'autoclose'=>true,
            'format' => 'yyyy-mm-dd',
            'todayHighlight' => true
        ]
    ]); ?>

    <?= $form->field($model, 'returned_date')->widget(DatePicker::classname(), [
        'options' => ['placeholder' => 'Date of Return'],
        'pluginOptions' => [
            'autoclose'=>true,
            'format' => 'yyyy-mm-dd',
            'todayHighlight' => true
        ]
    ]); ?>

    <?= $form->field($model, 'book_id')->widget(Select2::classname(), [
        'data' => $books,
        'options' => ['placeholder' => 'Select the book'],
        'pluginOptions' => [
            'allowClear' => false
        ],
    ]); ?>

    <?= $form->field($model, 'user_id')->widget(Select2::classname(), [
        'data' => $readers,
        'options' => ['placeholder' => 'Select the reader'],
        'pluginOptions' => [
            'allowClear' => false
        ],
    ]); ?>

    <?= $form->field($model, 'status')->dropDownList($model->getStatusArray()) ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/borrowing/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model app\models\Borrowing */

$this->title = Yii::t('app', 'New Book Loan');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'All Books Request'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="borrowing-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'books' => $books,
        'readers' => $readers
    ]) ?>

</div>

views/borrowing/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use Carbon\Carbon;
/* @var $this yii\web\View */
/* @var $searchModel app\models\BorrowingSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'All Books Request');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="borrowing-index">
    <?php if (Yii::$app->session->hasFlash('zeroExistence')): ?>
        <div class="alert alert-warning alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <?= Yii::t('app', 'Zero in Inventory?!? Seem like all are out there. Request more copies!'); ?>
        </div>
    <?php endif; ?>

    <h1><?= Html::encode($this->title) ?></h1>
    <p>
        <?= Html::a(Yii::t('app', 'Add New Book Loan'), ['create'], ['class' => 'btn btn-success']) ?>
    </p>
<?php Pjax::begin(); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'rowOptions'=> function($searchModel) {
            if($searchModel->isOverdue()) {
                return ['class' => 'danger'];
            }
        },
        'columns' => [
            [
                'attribute' => 'book_id',
                'filter' => false,
                'format' => 'raw',
                'value' => function($searchModel) {
                    return Html::a($searchModel->book->isbn, Url::toRoute(['/book/view', 'id' => $searchModel->book_id]));
                },
            ],
            [
                'attribute' => 'user_id',
                'filter' => false,
                'format' => 'raw',
                'value' => function($searchModel) {
                    return Html::a($searchModel->user->email, 'mailto:' . $searchModel->user->email);
                },
            ],
            'borrowed_date:date',
            'due_date:date',
            'returned_date:date',
            [
                'attribute' => 'status',
                'filter' => false,
                'format' => 'raw',
                'value' => function($model) {
                    return '<span class="label label-default">' . $model->getStatusArray()[$model->status] . '</span>';
                }
            ],

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

views/borrowing/overdue_lends.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use Carbon\Carbon;
use kartik\icons\Icon;
Icon::map($this);
/* @var $this yii\web\View */
/* @var $searchModel app\models\BorrowingSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Overdue Lends - Reader\'s Email');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'All Books Request'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="overdues-index">

    <?php if (Yii::$app->session->hasFlash('bookOverdue') || Yii::$app->session->hasFlash('bulkOverdue')): ?>
        <div class="alert alert-warning alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <?php
            if(Yii::$app->session->hasFlash('bookOverdue')) {
                echo Yii::t('app', 'Email was successfully sent to the Reader!');
            } elseif (Yii::$app->session->hasFlash('bulkOverdue')) {
                echo Yii::t('app', 'Bulk Email was successfully sent to all the Reader!');
            }
            ?>
        </div>
    <?php endif; ?>

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a(Yii::t('app', 'Send Bulk Email'), ['overdue-bulk'], [
                'class' => 'btn btn-warning',
                'data' => [
                    'method' => 'post',
                ]
            ]) ?>
    </p>

    <?php Pjax::begin(); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'rowOptions'=> function($searchModel) {
            if($searchModel->isOverdue()) {
                return ['class' => 'danger'];
            }
        },
        'columns' => [
            [
                'attribute' => 'book_id',
                'filter' => false,
                'format' => 'raw',
                'value' => function($searchModel) {
                    return Html::a($searchModel->book->isbn, Url::toRoute(['/book/view', 'id' => $searchModel->book_id]));
                },
            ],
            [
                'attribute' => 'user_id',
                'filter' => false,
                'format' => 'raw',
                'value' => function($searchModel) {
                    return Html::a($searchModel->user->email, 'mailto:' . $searchModel->user->email);
                },
            ],
            'borrowed_date:date',
            'due_date:date',
            'returned_date:date',
            [
                'attribute' => 'status',
                'filter' => false,
                'format' => 'raw',
                'value' => function($model) {
                    return '<span class="label label-default">' . $model->getStatusArray()[$model->status] . '</span>';
                }
            ],

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view}{send}',
                'buttons' => [
                    'send' => function ($url, $model) {
                        $url = Url::toRoute(['overdue-email', 'id' => $model->id]);
                        return Html::a(' ' . Icon::show('envelope'), $url, [
                            'title' => Yii::t('app', 'Send Email'),
                            'data' => [
                                'method' => 'post',
                            ]
                        ]);
                    },
                ]
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?></div>

views/borrowing/pickups.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use Carbon\Carbon;
use kartik\icons\Icon;
Icon::map($this);
/* @var $this yii\web\View */
/* @var $searchModel app\models\BorrowingSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Books for Pickup');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'All Books Request'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="pikups-index">

    <?php if (Yii::$app->session->hasFlash('zeroExistence')): ?>
        <div class="alert alert-warning alert-dismissible fade in" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <?= Yii::t('app', 'Zero in Inventory?!? Seem like all are out there. Request more copies!'); ?>
        </div>
    <?php endif; ?>

    <h1><?= Html::encode($this->title) ?></h1>

    <?php Pjax::begin(); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'attribute' => 'book_id',
                'filter' => false,
                'format' => 'raw',
                'value' => function($searchModel) {
                    return Html::a($searchModel->book->isbn, Url::toRoute(['/book/view', 'id' => $searchModel->book_id]));
                },
            ],
            [
                'attribute' => 'user_id',
                'filter' => false,
                'format' => 'raw',
                'value' => function($searchModel) {
                    return Html::a($searchModel->user->email, 'mailto:' . $searchModel->user->email);
                },
            ],
            'borrowed_date:date',
            'due_date:date',
            'returned_date:date',
            [
                'attribute' => 'status',
                'filter' => false,
                'format' => 'raw',
                'value' => function($model) {
                    return '<span class="label label-default">' . $model->getStatusArray()[$model->status] . '</span>';
                }
            ],

            [
                'class' => 'yii\grid\ActionColumn',
                'template' => '{view}{pickup}',
                'buttons' => [
                    'pickup' => function ($url, $model) {
                        $url = Url::toRoute(['pickup', 'id' => $model->id]);
                        return Html::a(' ' . Icon::show('vcard'), $url, [
                            'title' => Yii::t('app', 'Lend'),
                            'data' => [
                                'method' => 'post',
                            ]
                        ]);
                    },
                ]
            ],
        ],
    ]); ?>
    <?php Pjax::end(); ?></div>

views/borrowing/returned.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\helpers\Url;
use Carbon\Carbon;

/* @var $this yii\web\View */
/* @var $searchModel app\models\BorrowingSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('app', 'Books Returned');
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'All Books Request'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="returned-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <?php Pjax::begin(); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            [
                'attribute' => 'book_id',
                'filter' => false,
                'format' => 'raw',
                'value' => function($searchModel) {
                    return Html::a($searchModel->book->isbn, Url::toRoute(['/book/view', 'id' => $searchModel->book_id]));
                },
            ],
            [
                'attribute' => 'user_id',
                'filter' => false,
                'format' => 'raw',
                'value' => function($searchModel) {
                    return Html::a($searchModel->user->email, 'mailto:' . $searchModel->user->email);
                },
            ],
            'borrowed_date:date',
            'due_date:date',
            'returned_date:date',
            [
                'attribute' => 'status',
                'filter' => false,
                'format' => 'raw',
                'value' => function($model) {
                    return '<span class="label label-default">' . $model->getStatusArray()[$model->status] . '</span>';
                }
            ]
        ],
    ]); ?>
    <?php Pjax::end(); ?></div>

views/borrowing/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Borrowing */

$this->title = Yii::t('app', 'Loan by') . ' ' . ucfirst($model->user->getDisplayName()) ;
$this->params['breadcrumbs'][] = ['label' => Yii::t('app', 'All Books Request'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="borrowing-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php if(empty($model->borrowed_date)) : ?>
        <?= Html::a(Yii::t('app', 'Lend This Book'), ['pickup', 'id' => $model->id], [
            'class' => 'btn btn-success',
            'data' => [
                'method' => 'post',
            ],
        ]) ?>
        <?php endif; ?>
        <?php if($model->status > \app\models\Borrowing::STATUS_ON_HOLD) : ?>
            <?= Html::a(Yii::t('app', 'Return this Book'), ['return-book', 'id' => $model->id], [
                'class' => 'btn btn-warning',
                'data' => [
                    'confirm' => Yii::t('app', 'Are you sure everything is OK?'),
                    'method' => 'post',
                ],
            ]) ?>
        <?php endif; ?>
        <?= Html::a(Yii::t('app', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a(Yii::t('app', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => Yii::t('app', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'borrowed_date:date',
            'due_date:date',
            'returned_date:date',
            [
                'attribute' => 'book_id',
                'format' => 'raw',
                'value' => function($model) {
                    return Html::a('ID:' . $model->book_id . ' - ' . $model->book->title, Url::toRoute(['/book/view', 'id' => $model->book_id]));
                }
            ],
            [
                'attribute' => 'user_id',
                'value' => function($model) {
                    return 'ID:' . $model->user_id . ' - ' . $model->user->displayName;
                }
            ],
            [
                'attribute' => 'status',
                'format' => 'raw',
                'value' => function($model) {
                    return '<span class="label label-default">' . $model->getStatusArray()[$model->status] . '</span>';
                }
            ],
            'created_at:datetime',
            'updated_at:datetime',
        ],
    ]) ?>

</div>